language: rust
rust: 
  - stable

jobs:
  fast_finish: true

addons:
  apt:
    sources:
    - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial main'
      key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
    - llvm-10-tools
    - llvm-10-dev
    update: true