name: 'Rust LLVM build'
description: 'Action to build a rust project with an LLVM dependency'
inputs:
  llvm-sys-version:
    description: "Version of the LLVM to emulate (Required by llvm-sys)"
    required: false
    default: 11
  build-step:
    descritpion: "The build step to pass to cargo, (build, test..)"
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env: 
    'LLVM_SYS_${{inputs.llvm-sys-version}}0_PREFIX': '/usr/lib/llvm-${{inputs.llvm-sys-version}}'
  args:
  - '${{ inputs.build-step }}'
    

