name: Build

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  toolchain-version: 1.53.0
  llvm-version: "11.0.1"

jobs:
  check: 
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.toolchain-version }}
          profile: minimal
          override: true

      - name: Install LLVM
        uses: ghaith/install-llvm-action@v1
        with:
          version: ${{ env.llvm-version }}

      - name: Cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

  test:
    name: Test
    runs-on: ${{ matrix.config.os }}
    needs: check
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: "ubuntu-latest"}
          - { os: "windows-latest"}
    steps:

      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.toolchain-version }}
          profile: minimal
          override: true

      - name: Install LLVM
        uses: ghaith/install-llvm-action@v1
        with:
          version: ${{ env.llvm-version }}

      - name: Cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -- --nocapture

  style:
    name: Check Style
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.toolchain-version }}
          profile: minimal
          override: true
          components: clippy, rustfmt

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features -- -D warnings

