name: Build

on: [pull_request, push]

jobs:
  check: 
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install LLVM
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "11.0.1"

      - name: Cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

  style:
    name: Check Style
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: clippy, rustfmt

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Install LLVM
        uses: KyleMayes/install-llvm-action@v1

      - name: Run cargo clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

  # build:
  #   runs-on: ubuntu-latest
  #   name: Cargo Docker build  with LLVM-11
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v2
  #   - name: Cargo Build and Test
  #     uses: ./docker-build/
  #     with:
  #       build-step: 'test'
  #   - name: Formatter
  #     uses: ./docker-build/
  #     with:
  #       build-step: 'fmt'
  #       args: '-- --check'
  #   - name: Clippy
  #     uses: ./docker-build/
  #     with:
  #       build-step: 'clippy'
  #       args: '-- -D warnings'
